### ISSUE TITLE
Question: porting to Lisp?

### ISSUE THREAD

**Issue by eudoxia0** [roswell/roswell#104]
Over in #49 you said:

> 1. stability is the most important I don't want to debug the implementation for this project.
>    2.portability is important as well.same source code could be used for produce executable for different >CPUs at least Intel and Arm.
>    3.It should be well maintained on os Windows Linux osx.
>    4.the size of executables should be small enough for small memory environment.

I think for point 2., if CL doesn't run on that architecture/CPU, then there's not much of a point using it there. Plus, you might have systems that run, say, an embedded JVM, where you can't easily run C code but you can run ABCL.

For point 3., Common Lisp is fairly portable on Windows, Linux and OS X, if you're willing to use different implementations on different OS's, e.g. SBCL on Linux/OS X and CCL on Windows.

And for point 4. I don't think the executable size matters even in embedded systems. The executable will be at most a few tens of megabytes, and the Raspberry Pi has storage well into the multi-gigabyte range.

Plus, there's a cost to having multiple languages: every Common Lisp developer can contribute to a Roswell written in CL, but fewer developers know both CL and C well, and that reduces the pool of potential contributors.

If Roswell was available as a library you can Quickload, this would help it and its ecosystem.

If you decide to port it to CL I am totally willing to help port it.

**Comment by snmsts** [comment]
Thank you for important suggestion.
I admit that C is not good choice to potential contributors.
And it is also my bad that lack of comments and documents to support reading.

To chose implement language for Roswell,
I think Roswell's functionality are divided into two part.

* Introduce lisp for environment that has no lisp setup yet.
* manage lisp and other related projects (asdf and quicklisp)

I think I can increase second part that are already written in CL,but I have no idea about first part and how I can achieve it.
So far,I don't like to think about packaging matter for each environments, that's why C is convenient choice for me.

I have been thinking about making Roswell as a CL library. Don't worry about that part :)

**Comment by eudoxia0** [comment]
>Introduce lisp for environment that has no lisp setup yet.

Yeah, having to install Lisp manually to install a Lisp install manager defeats the point.

But when Roswell is more mature, that will only have to be done by people who want to build Roswell from source to develop it. Most users of Roswell will download binaries that have been built and uploaded to the repository.

The problem is you have to build it on every platform, for every version, but I think that's minor compared to the problem of having two separate implementation languages.

**Comment by proofit404** [comment]
Maybe we can setup automatic build uploading from CI server. This will allows us easily get most up-to-date versions of `master` and `production` branches on each platform.

Static site generators do this same way deploing github-pages from Travis-CI builds.

Also building roswell from source will be available after installing lisp with roswell binary.

**Comment by snmsts** [comment]
> But when Roswell is more mature, that will only have to be done by people who want to build Roswell from source to develop it. Most users of Roswell will download binaries that have been built and uploaded to the repository.

hm...
Who want to do that? At least I don't want to do it by myself now.
Is packaging activity would get easier when I decide to write it in Lisp? I doubt it.

> Maybe we can setup automatic build uploading from CI server.

At least I use roswell on chrome book flip. It works fine for me.
I don't know where is the appropriate CI server to automatically build roswell binary for RK3288C.
choosing binary for the machine is not easy task for me.
I hate to think about lisp's complicated portability and rely on c tool-chain's ubiquity and that motivate me to make Roswell.

It's fine to make the lisp codes reusable.I will.
But thinking about the initial motivation, I don't have interest so much.

I feel some C code must be preserved with this software.

**Comment by eudoxia0** [comment]
>At least I use roswell on chrome book flip. It works fine for me.
>I don't know where is the appropriate CI server to automatically build roswell binary for RK3288C.

Well, most users will probably be using it from Intel/AMD desktop computers as opposed to ARM machines.

Perhaps the ARM build can be a bit behind the most recent versions. SBCL builds on ARM now apparently.

**Comment by sionescu** [comment]
Hi @snmsts, you don't need to support multiple Lisps for the manager and neither to support environment with no Lisp configuration.

1) Choose the most portable open-source Lisp implementation: Clozure. Bundle the entire sources and update rarely. This way you control the compiler used and won't waste time with portability bugs or version incompatibility.
2) Bundle all CL libraries and have a build script that ignores any outside ASDF configuration, so that it works anywhere.

Initially - the first few years - you will only support the use of this new tool as command-line executable. 
Once the code is stable, you can work on allowing it to be used as a library and port it to other CL implementations, but in the beginning it's essential to focus on the most important goal: making it work, not making it portable.

At least, this is my (strong) opinion.

**Comment by snmsts** [comment]
I'm not so tempted with the idea, but I feel I'll use current roswell to implement C-free roswell instead of Clozure.

**Comment by snmsts** [comment]
I felt it's not my business.
