### ISSUE TITLE
How to use Roswell to run code from my GitHub repo and take PRs into account and find test system?

### ISSUE THREAD

**Issue by MatthewRock** [roswell/roswell#232]
Hi. I don't want to open a new issue, since it kinda relates to the old one, so I thought I'd just reopen this one.

Right now I have noticed that the scheme I took previously - the one with the roswell - doesn't really work with (a) proper tests, (b) test package.

So let me explain (a); previously, I have been trying to test my system using (asdf:test-system 'cl-sandbox) . This doesn't really work; you always get T. However, this makes asdf look up how to test the system, realize that it has to get cl-sandbox/tests system, gets it and runs its test-op. Everything fine here.

So now, I have to change the way I do tests. Now I call the tests directly. HOWEVER, this does not work...

So the problem is: Roswell (or rather quicklisp) doesn't see my tests system! That's a huge problem because I can't invoke the tests. It's strange to me, since asdf can see the main package and test it.

Now what could be the cause? How should I set up the Travis's yml and roswell script so that the PRs are tested properly too?

For the reference, here are the links to

    the repo: https://github.com/MatthewRock/cl-sandbox/tree/fix-tests/
    the travis file: https://github.com/MatthewRock/cl-sandbox/blob/fix-tests/.travis.yml
    said roswell file: https://github.com/MatthewRock/cl-sandbox/blob/fix-tests/roswell/cl-sandbox-test.ros

I have this repository locally on my machine under the path specified in :tree asdf's option. I can load both systems and run tests in my REPL without any problem.

PS.
Since my comment into the thread that kinda started this seemed like not enough for some reason, here goes new issue.

#225 is the original one.

As for reproducing,
you can either locally run scripts found in .yml file in the repo that I have provided link to, or fork the repository and add it to the TravisCI for the full experience.

**Comment by snmsts** [comment]
I think you've already have travis failure result.
Why don't you share it and point out where the problem?

**Comment by MatthewRock** [comment]
Right, sorry. I  thought it was obvious when I was referring to the previous issue, but it seems I lack some communication skills :)

As I said, the problem is that the *test* system is not found. The test system is defined in the same .asd file as the main system. Here is Travis screenshot of the problem.

![screenshot-20170427 152525](https://cloud.githubusercontent.com/assets/1909226/25481382/345bed62-2b4d-11e7-946b-607691690586.png)

As I said, when the repository is in my asdf's :tree directory, quickloading it works just fine.

**Comment by Hexstream** [comment]
A screenshot of text?! You should probably use triple-backtick code block quoting in that context:

\```
Your big backtrace
\```

:arrow_down:

```
Your big backtrace
```

(You can also replace your screenshot of text by the quoted text directly in your comment by editing it.)

**Comment by MatthewRock** [comment]
What is the problem with screenshot of text? Is the text not readable? There is no need for the big backtrace. The problem is:

```
The package "CL-SANDBOX/TESTS" can't be found.
```
just like I said in OP

**Comment by snmsts** [comment]
it's too trivial. Don't read any symbols in a package which are not yet defined.

**Comment by snmsts** [comment]
and it's not issue for us.

**Comment by MatthewRock** [comment]
Thank you for the solution. Using eval-when seems to solve the one of the problems.

I would also like to express my gratitude to those who help in here. The unique mix of kindness, eagerness to help and respect towards the users results in the welcoming atmosphere that makes me want to come back and promote this project, especially its helpful developers who go out of their way to help others.

**Comment by guicho271828** [comment]
urgh, honestly, I do not want to be involved. But @MatthewRock , from all my sincerity I recommend [this article](http://www.catb.org/esr/faqs/smart-questions.html) for you ... seriously, you are violating multiple points in the article. 

+ [Use meaningful, specific subject headers](http://www.catb.org/esr/faqs/smart-questions.html#bespecific) --- I'd use a title such as "When I call asdf:test-system on my system in a roswell script on travis, it dies with `package CL-SANDBOX/TESTS can't be found`". If the title was as clear as this, then answering your question should have been much easier! That immediately means that you are referring to an undefined package. Only 1 reply was necessary, life is short!
+ [Write in clear, grammatical, correctly-spelled language](http://www.catb.org/esr/faqs/smart-questions.html#writewell) --- you might or might not be fluent in English, I have no idea on the Internet. English is not my native language (@snmsts either.) However, aside from the fluency, you were basically like: "I did X, so Y, so Z, but W, so I did R, but I did S..." --- I mean unstructured and is not very friendly to the readers.
+ [Send questions in accessible, standard formats](http://www.catb.org/esr/faqs/smart-questions.html#formats) --- this is regarding images. It prevents copy-pasting texts, the font is actually hard to read on a large screen, and any other problems arose from a non-standard format. Do not do anything surprising, it is unnecessary and saves everyone's time.
+ Similarly, don't *describe* how to reproduce it by words, but paste the *complete code* that reproduces it, so that the maintainers can reproduce it easily. This is about accessibility.
+ [Don't rush to claim that you have found a bug](http://www.catb.org/esr/faqs/smart-questions.html#idm46680517890864) --- Also read ["It doesn't work"](www.chiark.greenend.org.uk/~sgtatham/bugs.html#respect).

And finally, please keep in mind [How To Interpret Answers -- Dealing with rudeness](http://www.catb.org/esr/faqs/smart-questions.html#keepcool) --- In case if you somehow end up thinking that what you experienced here is *specific* to lisp community. That is not true.

**Comment by snmsts** [comment]
@MatthewRock I'm appreciate you find the way. 
@guicho271828 Thank you very much. I could use this as template before I become rude.

**Comment by MatthewRock** [comment]
@guicho271828 
Wow, could you look at that. An actual answer that points out the problems and suggests the solutions? I can't believe my eyes.

Seriously, I am fine with your answer. I like it. You might not like my whining or my question (for whatever reason), but you suggest actual solutions and use neutral, helpful tone. Did that cost you anything?

By the way, thanks for the article and tips.

I made some mistakes; maybe I should have been more concise. I am not really good at making a good titles for questions, but I'm learning. The reason I did not post the backtrace is that I have already done that - in the PR I am referencing. I actually reopened it, because of the same underlying issue(can't find a package), but I've been told to "open a new issue and don't blow it off explaining how to reproduce the problem for us.". Now after asking again how to solve the problem, I learn that "it's not issue for us.". Seriously?

I'm not trying to be ungrateful or rude. I am aware that I'm asking someone to help me fix my problem. I am aware that this is likely due to me messing things up. But instead of saying "It's too trivial", he could have easily said "The issue here is that you are doing X. Try doing Y instead.". Boom! No rudeness at all. Is this really that hard?

I'm fine with direct, concise answers. I'm not fine with rudeness, and trying to explain this with "hacker etiquette" is ludicrous. I've never said it's specific to lisp community, but because it's so small, we should try to make sure we are as welcoming as we can. Look at Haskell guys; you ask a dumb question, they (very kindly) help you with it. You try to troll them, you learn new things instead. Compare that to @snmsts  and no wonder Haskell's getting more popular despite it being younger than CL.

Anyway, thanks for the link. I don't agree with it as a whole, but it has useful parts.

**Comment by guicho271828** [comment]
You seem overreacting --- "it's not issue for us." just means its not a bug in roswell but in your code.

The reason @snmsts responded that way is that you already violated the rules in #225 and keep violating in sequence here #232, which made him less motivated in helping you. I think it is quite understandable. In fact, he is responding nicely to the other people who posts clear bug reports.

**Comment by MatthewRock** [comment]
> you already violated the rules in #225 and keep violating in sequence here #232

He said that where, exactly? I can't find any "Please follow our guideline found <somewhere>" or kind of post you posted up there.

**Comment by guicho271828** [comment]
He didn't wrote it anywhere explicitly but it is just a standard way to report bugs. Most people can do it.

Drink some coffee and do some other hacking for the time being. Wait for one week and see if you still remember this topic, in which case you can come back here.
