### ISSUE TITLE
ros emacs invoked default old emacs

### ISSUE THREAD

**Issue by abeq** [roswell/roswell#267]
I have tried "ros emacs" on OS X 10.11.6.
But default Emacs on OS X 10.11.6 is version 22.1.1 and Slime requires Emacs version 23. 
I have installed Emacs version 25.3.1 and made alias "emacs" with new emacs path.
But "ros emacs" invoked default emacs still now.
Is there way to correct to invoke with new emacs?

**Comment by guicho271828** [comment]
Roswell calls emacs directly with `exec`, so you can't expect that the shell expands your alias. However `exec` should recognize `PATH`, so instead of making an alias for the shell, you can make a symlink to the new emacs in a place such as `~/bin/`, and put `~/bin/` in `PATH` so that the new emacs overrides the old emacs.

**Comment by guicho271828** [comment]
I guess you put the alias somewhere in a rcfile like `.bashrc` or `.zshrc`, and aliases are shell specific things. So it won't work if you switch to another shell like `dash`. In contrast `PATH` method should work on any shells if you set up the variable in `.profile` and export it.

**Comment by abeq** [comment]
Thank you for your answer. I will try to fix it.
