### ISSUE TITLE
compile error on cygwin

### ISSUE THREAD

**Issue by damon-kwok** [roswell/roswell#345]
## Environment
windows10+cygwin
```
# result of evaluating
uname -a
```
````
CYGWIN_NT-10.0 DESKTOP-EKK7E17 2.11.1(0.329/5/3) 2018-09-05 10:24 x86_64 Cygwin
````

# configure
```sh
sh bootstrap
./configure --prefix=$OME_PREFIX
```
<details>
checking for a BSD-compatible install... /bin/install -c

checking whether build environment is sane... yes

checking for a thread-safe mkdir -p... /bin/mkdir -p

checking for gawk... gawk

checking whether make sets $(MAKE)... yes

checking whether make supports nested variables... yes

checking whether to enable maintainer-specific portions of Makefiles... yes

checking for gcc... gcc

checking whether the C compiler works... yes

checking for C compiler default output file name... a.exe

checking for suffix of executables... .exe

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether we are using the GNU C compiler... yes

checking whether gcc accepts -g... yes

checking for gcc option to accept ISO C89... none needed

checking whether gcc understands -c and -o together... yes

checking for style of include used by make... GNU

checking dependency style of gcc... gcc3

checking for main in -lwininet... yes

checking windows.h usability... yes

checking windows.h presence... no

configure: WARNING: windows.h: accepted by the compiler, rejected by the preprocessor!

configure: WARNING: windows.h: proceeding with the compiler's result

checking for windows.h... yes

checking for windres... windres

checking that generated files are newer than configure... done

configure: creating ./config.status

config.status: creating Makefile

config.status: creating src/Makefile

config.status: creating documents/Makefile

config.status: creating config.h

config.status: config.h is unchanged

config.status: executing depfiles commands

</details>

# make install
# configure
```sh
make install
```
<details>
Making install in src

make[1]: Entering directory '/home/damon/.dev/roswell/src'

gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT ros.o -MD -MP -MF .deps/ros.Tpo -c -o ros.o ros.c
In file included from opt.h:4:0,
                 from ros.c:2:

util.h:33:10: fatal error: direct.h: No such file or directory
 #include <direct.h>

          ^~~~~~~~~~

compilation terminated.

make[1]: *** [Makefile:460: ros.o] Error 1

make[1]: Leaving directory '/home/damon/.dev/roswell/src'

make: *** [Makefile:554: install-recursive] Error 1

</details>

**Comment by snmsts** [comment]
hmm... cygwin is out of focus for years...

**Comment by manugoswami** [comment]
Hi Masatoshi San,

Kindly suggest any way to remove this error and install ROSWELL in CYGWIN.

Please give some idea why this **_might_** be failing

Warm Regards,
manu

**Comment by snmsts** [comment]
direct answer for how to solve the error is what does this error mean is cygwin doesn't have dirent.h so check all the dependency of dirent.h on roswell and find replacement on cygwin and properly take care `configure.ac` and other part would make it fine. It's trivial but I don't know how many lines should be edited for fix it.

I planed to support cygwin when I started this project and I have lost interest (in 2 years I think) because.
* virtualization support on windows is good enough. so lisp developers should use linux environment on windows
* mingw/msys2 environment is better for compile app and would't add cygwin1.dll dependency so lisp app distributors should use msys2 for windows.
* cygwin has some tricky incompatibility (not clearly remembered how and it might be my misunderstanding. sorry) with sbcl which roswell tightly depends on.

Situation on cygwin might be changed but not sure already. I haven't been updated and have no struggle on it. 

I'm personally curious about benefit of cygwin over linux virtual machine or msys2.

**Comment by manugoswami** [comment]
Hi Masatoshi San,

Where from the direct.h was taken? was it MSYS or BOOST or some other library?

Warm Regards,
Manu

**Comment by snmsts** [comment]
help yourself please...

**Comment by manugoswami** [comment]
OK Dear. The issue is closed from my side also. From my perspective CYGWIN is wonderful development environment in windows. simple and straight forward. Dosen't hide anything from any one and has a very wide support. Anything done which does not take CYGWIN into account is certainly on a wrong path as CYGWIN is what an ideal development platform should be in windows . Small and very effective. Anything dependent on windows is bound to fail as microsoft changes things , mostly which are not in line with good individual software development.

**Comment by snmsts** [comment]
Now I do understand your attachment to cygwin but there seems no benefit to support cygwin for my perspective.
supporting cost is too much and I want spend more time on development.
Please don't forget cygwin is not tested well by sbcl for decades. I completely disagree with your impression of cygwin is straight forward, at least it requires huge patch to support for some software.
I gave up try supporting cygwin because of the difficulty to manage common lisp on cygwin after at least a few month of effort.
I recommend you to switch cygwin to msys2 or forget about common lisp.

**Comment by manugoswami** [comment]
Dear Masatoshi San,

I am not in favour of CYGWIN but i am definitely impressed by its simplicity. Only experience gives simplicity.

Take a look at this website. Probably it might help you too. Anyway lets close this discussion. It would be nice if ROSWELL is available on CYGWIN.

https://wiki.wxwidgets.org/Cygwin#:~:text=5%20Troubleshooting-,To%20set%20up%20wxWidgets%20using%20Cygwin,make



To get an executable independent of Cygwin DLL
Normally if you compile with Cygwin's GCC, any executables you create will depend on the Cygwin DLL, forcing you to distribute your application with the DLL. There is, however, a workaround. Including -mno-cygwin in CFLAGS/LDFLAGS in configure.in makes Cygwin's GCC compile and link against only native windows libs. Compiling wxWidgets apps with this option has been reported to work flawlessly - at least for wxWidgets 2.6.2. See http://www.delorie.com/howto/cygwin/mno-cygwin-howto.html for more information. See also the warning in the configure.in comments about mno-cygwin and the math library.

Warm Regards,

Manu
