### ISSUE TITLE
Windows binary missing

### ISSUE THREAD

**Issue by jcs090218** [roswell/roswell#555]
The last two releases do not have Windows' binary. What happened? 🤔 

- [v22.12.14.112](https://github.com/roswell/roswell/releases/tag/v22.12.14.112)
- [v22.12.14.113](https://github.com/roswell/roswell/releases/tag/v22.12.14.113)

Latest release with Windows binary available:

- [v21.10.14.111](https://github.com/roswell/roswell/releases/tag/v21.10.14.111)

**Comment by snmsts** [comment]
I don't know how CI broken but it's because of CI and I didn't care because it's easy to install roswell on mingw64 environment. https://packages.msys2.org/package/mingw-w64-x86_64-roswell?repo=mingw64

**Comment by jcs090218** [comment]
Thank you for your information. I personally don't recommend people using mingw64 since most ported software is fragile and ends up with okayish or bad UX. 😓

**Comment by toracle** [comment]
I found that windows build was still failing after #565 was merged. I looked into it and found that there were two windows build files, `.github/workflows/windows.yml` and `.github/workflows/build.yml`, that were very similar. I only fixed one of them (`windows.yml`).

So, I think there are two possible solutions:

* They are duplicated, due to some historical reason, so we can remove one (build.yml?)
* They are not duplicated, but intentional. So, we need to apply #565 patch (install autotools) to `build.yml` as well.

I’m not sure about the purpose of `build.yml`, so maybe someone from the maintainers can explain it.
